### ISSUE TITLE
Knobs not working properly

### ISSUE THREAD

**Issue by alexssung** [bitwig/native-instruments-komplete-kontrol#1]
Using a S61 and the script bundled with Bitwig:

The knobs are simply not working properly. In device and track modes, the knobs change value very slowly until they hit a midi value of 64, then they become hypersensitive going the other direction.

I took a look at the code and noticed:

```javascript
var inc = 0;
      if (data2 < 64) {
         inc = data2;
      }
      else {
         inc = -(128 - data2);
      }
```

I don't understand why the inc value is set this way? 
Maybe the new Kontrol firmware updated the way they send midi values.

**Comment by ThomasHelzle** [comment]
I'm no longer involved with these scripts and don't have the controller to try, but did you install the template? See the helpfile for the script, upper right corner...
The script works that way since the unit sends values in incremental mode as values from 0 to 63 when you turn the knob in one direction and from 64 to 127 if you turn it the other way. The logic you posted sorts those two and negates one of them do decrease the value.
This is why you need to install and activate the template, so the KK is in the right mode...

I don't know what changed in the latest firmware - if they changed the way the unit is sending data, Bitwig would have to change the script accordingly.

**Comment by alexssung** [comment]
My apologies, did not know we needed to install a template.

Works fine on my Bitwig now. Thanks.
